<a href="https://colab.research.google.com/github/yejin0455/sesac-python/blob/main/%ED%86%B5%EA%B3%84%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D_%EC%A3%BC%EC%9A%94_%EB%AA%A8%EB%93%88_%ED%95%99%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기본

In [1]:
ls = [1, 2, 3, 4, 5]

ls_twice = []
for e in ls:
    ls_twice.append(e*2)
ls_twice

[2, 4, 6, 8, 10]

In [2]:
import numpy as np
arr = np.array(ls)
arr_twice = arr * 2
arr_twice

array([ 2,  4,  6,  8, 10])

강한 wrapping

In [3]:
arr = np.arange(10000)
arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [4]:
arr = np.array(range(10000))
arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

wrapping 이란?

In [5]:
def madd(a, b):
    return a + b

In [6]:
def msum(ls):
    s = 0
    for e in ls:
        s = madd(s, e)
    return s

In [7]:
def count(ls):
    cnt = 0
    for _ in ls:
        cnt += 1
    return cnt

In [8]:
ls = [1, 2, 3, 8, 4]
s = msum(ls)
l = count(ls)
print(f'평균:{s/l:.2f}')

평균:3.60


In [9]:
def average(ls):
    return msum(ls) / count(ls)

In [10]:
print(f'평균:{average(ls):.2f}')

평균:3.60


# tensor

In [11]:
data = np.random.rand(5, 2, 3)
data

array([[[0.81891167, 0.94956035, 0.11545752],
        [0.51528123, 0.5790768 , 0.89654594]],

       [[0.44987701, 0.9651807 , 0.56467298],
        [0.57164791, 0.29557038, 0.53668339]],

       [[0.28740372, 0.34151131, 0.21062314],
        [0.81310661, 0.58157363, 0.40554988]],

       [[0.09002451, 0.5992352 , 0.53906512],
        [0.66224716, 0.08382112, 0.38656492]],

       [[0.16327007, 0.56084315, 0.59310274],
        [0.39222917, 0.03664007, 0.89823658]]])

In [12]:
data.shape

(5, 2, 3)

In [13]:
data2 = data.reshape(6, -1)
data2

#data2 = data.reshape(7, -1)  #요구하는 구조로 정확하게 구성하지 못함
#data2

array([[0.81891167, 0.94956035, 0.11545752, 0.51528123, 0.5790768 ],
       [0.89654594, 0.44987701, 0.9651807 , 0.56467298, 0.57164791],
       [0.29557038, 0.53668339, 0.28740372, 0.34151131, 0.21062314],
       [0.81310661, 0.58157363, 0.40554988, 0.09002451, 0.5992352 ],
       [0.53906512, 0.66224716, 0.08382112, 0.38656492, 0.16327007],
       [0.56084315, 0.59310274, 0.39222917, 0.03664007, 0.89823658]])

In [14]:
data2.shape

(6, 5)

In [15]:
#파이썬의 리스트는 tensor 자료가 아닐 수 있다
zagged_arr = [[1, 2, 3], [1, 2], [1, 2, 3, 4, 5]]
zagged_arr

[[1, 2, 3], [1, 2], [1, 2, 3, 4, 5]]

In [19]:
data2.ndim

2

# 행렬 계산

In [16]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[4, 6], [3, 7]])

arr3 = arr1 + arr2
arr3

array([[ 5,  8],
       [ 6, 11]])

In [18]:
ls1 = [[1, 2], [3, 4]]
ls2 = [[4, 6], [3, 7]]

ls3 = ls1 + ls2
ls3

[[1, 2], [3, 4], [4, 6], [3, 7]]

# 원소 형식

In [25]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1.dtype

dtype('int64')

In [26]:
type(arr1[0])

numpy.int64

In [27]:
arr2 = np.array([1, 2, 3, 4, 5.])
arr2.dtype

dtype('float64')

In [28]:
type(arr2[0])  #numpy에 들어있는 원소의 형식은 전부 같다

numpy.float64

In [29]:
arr3 = np.array([1, 2, 'a', 4, 5])
arr3.dtype

dtype('<U21')

In [30]:
type(arr3[0])

numpy.str_

In [31]:
arr3[0]

'1'

In [32]:
ls = [1, 2, 3, 4, 5.]  #리스트는 원소가 서로 다른 타입이어도 저장된다
type(ls[0]), type(ls[4])

(int, float)

# 형식 변환

In [33]:
arr4 = np.array(['1', '2', '3', '4'])
for e in arr4:
    print(e, end=',')
print()

1,2,3,4,


In [34]:
s = arr4[0]
for e in range(1, len(arr4)):
    s += arr4[e]
print(s)

1234


In [35]:
arr5 = arr4.astype(int)
print(arr5.sum())

10


# 산술 연산, 필터링

In [36]:
arr = np.array([[1, 2], [3, 4]])
sq_arr = arr * arr
sq_arr

array([[ 1,  4],
       [ 9, 16]])

In [37]:
d5_arr = arr/5
d5_arr

array([[0.2, 0.4],
       [0.6, 0.8]])

In [38]:
arr = np.array([-1, 2, 3, 4, -4, 9])
filter = arr >= 0
print(filter)
darr = arr[filter]
print(darr)

[False  True  True  True False  True]
[2 3 4 9]


In [39]:
arr = np.array([-1, 2, 3, 4, -4, 9])
filter = arr%2 == 0
print(filter)
darr = arr[filter]
print(darr)

[False  True False  True  True False]
[ 2  4 -4]


In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape

(2, 3)

In [41]:
for i in range(2):
    for j in range(3):
        print(arr[i, j], end=',')
    print()

1,2,3,
4,5,6,


In [42]:
print(arr[0, 1])
print(arr[0][1])

2
2


In [43]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
arr[3:10]  #arr[3]~arr[10-1]

array([3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[95:]

array([95, 96, 97, 98, 99])

In [47]:
arr[-1]

99

In [48]:
arr[90:-3]  #뒤에서 3개를 제외하고

array([90, 91, 92, 93, 94, 95, 96])

In [49]:
pre80 = arr[:len(arr)*4//5]
pre80

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [50]:
post20 = arr[len(arr)*4//5:]
post20

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99])

# 필터링 강화

In [53]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
scores = np.array([90, 80, 74, 85, 78, 88, 85])
filter = names == 'Bob'
scores[filter]

array([90, 85])

In [54]:
texts = np.array(["Hello, How are you?", "Where r u from?", "RD GG", "ready Go Go"])
filter = [True if "r" in text else False for text in texts]
filter
texts[filter]

array(['Hello, How are you?', 'Where r u from?', 'ready Go Go'],
      dtype='<U19')

컴프리핸션

In [55]:
data = [i*i for i in range(10)]
print(data)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [56]:
data2 = [i*i for i in range(10) if i%2==0]
print(data2)

[0, 4, 16, 36, 64]


In [57]:
data3 = [i*i if i%2==0 else -(i*i) for i in range(10)]
print(data3)

[0, -1, 4, -9, 16, -25, 36, -49, 64, -81]
