<a href="https://colab.research.google.com/github/yejin0455/sesac-python/blob/main/%ED%86%B5%EA%B3%84%EB%B6%84%EC%84%9D%EC%8B%9C%EA%B0%81%ED%99%94_Numpy_More.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 행렬의 기본 연산

In [1]:
import numpy as np

In [3]:
ls1 = [1, 2]
ls2 = [3, 4]
ls3 = ls1 + ls2
print(ls3)

[1, 2, 3, 4]


In [5]:
s = 0
for i in range(10):
    s += i

assert s == 45, "s는 45여야 합니다"

In [ ]:
#ls 목록에 있는 요소의 합계를 구하는 함수
def calsum(ls):
    s = 0
    for e in ls:
        s += e
    return s

In [ ]:
assert calsum([1, 2, 3, 2]) == 8, "calsum([1, 2, 3, 2]) 값은 8이어야 합니다"

In [6]:
def add(l1, l2):
    assert len(l1) == len(l2), "더하기 연산을 위해서는 요소의 길이가 같아야 됨"
    re = []
    for i in range(len(l1)):
        re.append(l1[i] + l2[i])
    return re

In [7]:
ls1 = [1, 2]
ls2 = [3, 4]
ls3 = add(ls1, ls2)
print(ls3)

[4, 6]


In [8]:
n1 = np.array([1, 2])
n2 = np.array([3, 4])
n3 = n1 + n2
print(n3)

[4 6]


In [9]:
n3 = n1 - n2
print(n3)

[-2 -2]


In [10]:
ls1 = [1, 2, 3, 4]
ls2 = ls1 * 3
print(ls2)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [11]:
n1 = np.array([1, 2, 3, 4])
n2 = n1 * 3
print(n2)

[ 3  6  9 12]


In [12]:
n2 = n1/3
print(n2)

[0.33333333 0.66666667 1.         1.33333333]


In [13]:
n1 = np.random.randint(1, 1000, 100, dtype=int)
print(n1)

[125 371 161 676 618 758 984 856 852 955 933 854 343 744 405 353 210 596
 364 358 769 604 922 402  31  73 343 850 256 898 262 502 515 362 193 143
 724 146 511  17 780 305 227 976 294 937 837 375 447 421 615 914 666 989
 785 717 819 301 689 624 113 308 549 703 335 371 554 855  84 767 720  25
 283  69 995 804 147 133 148  16 834 268 409 414 825 922 298 448 628 404
 260 726 578 423 874 576 293 958 288 398]


In [14]:
n2 = n1 > 500
print(n2)

[False False False  True  True  True  True  True  True  True  True  True
 False  True False False False  True False False  True  True  True False
 False False False  True False  True False  True  True False False False
  True False  True False  True False False  True False  True  True False
 False False  True  True  True  True  True  True  True False  True  True
 False False  True  True False False  True  True False  True  True False
 False False  True  True False False False False  True False False False
  True  True False False  True False False  True  True False  True  True
 False  True False False]


In [15]:
n3 = n1[n2]
print(n3)

[676 618 758 984 856 852 955 933 854 744 596 769 604 922 850 898 502 515
 724 511 780 976 937 837 615 914 666 989 785 717 819 689 624 549 703 554
 855 767 720 995 804 834 825 922 628 726 578 874 576 958]


In [16]:
n1 = np.array([[1, 2], [3, 4]])
n2 = np.array([4, 5])
n3 = np.dot(n1, n2)
print(n3)

[14 32]


In [17]:
n1 = np.array([1, 2, 3, 4])
n2 = n1.reshape((2, 2))
print(n2)

[[1 2]
 [3 4]]


In [18]:
n3 = np.transpose(n2)
print(n3)

[[1 3]
 [2 4]]


In [ ]:
n3 = np.invert(n2)  #반전(원소의 메모리)
print(n3)

In [ ]:
n3 = np.linalg.inv(n2)  #역행렬
print(n3)

In [21]:
n4 = n2.dot(n3)
print(n4)

[[-10 -13]
 [-22 -29]]


In [22]:
n1 = np.array([1, 2, 3, 4])
n2 = n1 - 3
print(n2)

[-2 -1  0  1]


In [23]:
n2 = n1/3
print(n2)

[0.33333333 0.66666667 1.         1.33333333]


# 통계 관련

In [26]:
n1 = np.random.randint(1, 100, 30, dtype=int)
print(n1)

[94 70 75 65 39 27 23 24 10 88 65 57 10 72 98 23 85 77 27 80 89 66 81 38
 60 98 59 50 25 64]


In [27]:
print("길이:", len(n1))

길이: 30


In [28]:
print("평균:", n1.mean())

평균: 57.96666666666667


In [29]:
n2 = n1 - n1.mean()
print("수평 이동한 후 평균:", n2.mean())

수평 이동한 후 평균: -1.8947806286936005e-15


In [30]:
print("최대값 위치:", n1.argmax())
print("최대값:", n1[16])
print("최대값:", n1.max())

최대값 위치: 14
최대값: 85
최대값: 98


In [31]:
print("분산:", n1.var())

분산: 711.4322222222221


In [32]:
print("표준편차:", n1.std())

표준편차: 26.67268682045778


In [33]:
n2 = n1/n1.std()
print("스케일 조절한 후 표준 편차:", n2.std())

스케일 조절한 후 표준 편차: 0.9999999999999999


In [37]:
print("최소값:", n1.min())
print("중앙값:", np.median(n1))  # .np정적메소드로 접근
print("1/4분위값:", np.percentile(n1, 25))
print("3/4분위값:", np.percentile(n1, 75))

최소값: 1
중앙값: 5.0
1/4분위값: 3.0
3/4분위값: 7.0


In [35]:
print(n1)
print("누적 합:", np.cumsum(n1))

[94 70 75 65 39 27 23 24 10 88 65 57 10 72 98 23 85 77 27 80 89 66 81 38
 60 98 59 50 25 64]
누적 합: [  94  164  239  304  343  370  393  417  427  515  580  637  647  719
  817  840  925 1002 1029 1109 1198 1264 1345 1383 1443 1541 1600 1650
 1675 1739]


In [36]:
n1 = np.arange(1, 10)
print(n1)
print("누적 곱:", np.cumprod(n1))

[1 2 3 4 5 6 7 8 9]
누적 곱: [     1      2      6     24    120    720   5040  40320 362880]
